### ISSUE TITLE
Immutables 2.12.2 downgrades JUnit from 6.x to 5.x for Spring Boot 4.0 application

### ISSUE THREAD

**Issue by breun** [immutables/immutables#1659]
I use Immutables 2.12.1 in a Spring Boot 4.0.6 application. Updating to Immutables 2.12.2 however failed the build, because suddenly JUnit 5 was used instead of JUnit 6, resulting in `NoSuchMethodError` exceptions. It seems that Immutables 2.12.2 added `<dependencyManagement>` entries for `org.junit:junit-bom` (and `com.fasterxml.jackson:jackson-bom` and `tools.jackson:jackson-bom`), which interferes with Spring Boot's managed dependencies.

**Comment by asereda-gs** [comment]
I think it was introduced by 83cdfdb and 8afa8127d which added BOM for JUnit and Jackson.

Can you reorder your dependencies to see if it helps?

**Comment by breun** [comment]
Not really, the dependencies managed by the Spring Boot framework are inherited via the parent.

**Comment by elucash** [comment]
Maybe we should separate junit / jackson - third-party dependencies, which are test-only or optional into separate bom pom, which we can reuse internally, but avoid propagating any of these to anyone who uses immutables-bom to just line up versions of immutables. So our Junit (which is test only) would not interfere with other frameworks (their choice of pom/bom strategy is up to them, i.e. what to bom or not)

**Comment by breun** [comment]
I have this BOM import for Immutables:

```
      <dependency>
        <groupId>org.immutables</groupId>
        <artifactId>bom</artifactId>
        <version>${immutables.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
```

`org.immutables:bom` has `org.immutables:immutables` as its parent, and `org.immutables:immutables:2.12.2` contains:

```
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.fasterxml.jackson</groupId>
        <artifactId>jackson-bom</artifactId>
        <version>${jackson.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>tools.jackson</groupId>
        <artifactId>jackson-bom</artifactId>
        <version>${jackson3.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>org.junit</groupId>
        <artifactId>junit-bom</artifactId>
        <version>${junit5.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
```

This means that any project that imports `org.immutables:bom:2.12.2` also imports Immutables' dependency management of Jackson 2, Jackson 3 and JUnit 5, so it is not a clean BOM.

The Immutables BOM should only provide dependency management for Immutables modules. Also see Maven's documentation on [Bill of Materials (BOM) POMs](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Bill_of_Materials_.28BOM.29_POMs).

I think `org.immutables:bom` needs to lose `org.immutables:immutables` as its parent. If this can not be done directly, it may be possible to use the [flatten-maven-plugin](https://www.mojohaus.org/flatten-maven-plugin/) produce a clean BOM POM for end users, because it has specific features for this.

**Comment by asereda-gs** [comment]
Can you please confirm that it works following @elucash's change in 4eab932 ?
